apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
spec:
  containers:
  - name: app
    image: "020549807535.dkr.ecr.us-east-1.amazonaws.com/devops:latest"
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: prod
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
