apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  labels:
    app: go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
  spec:
      containers:
        - name: goapp
          image: <ECR_REPO_URL>
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: goapplication-service
spec:
  selector:
    app: go
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort